apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-green
  labels:
    app: demo-pod-green
    version: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-pod-green
      version: default
  template:
    metadata:
      labels:
        app: demo-pod-green
        version: default
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: demo-pod-green
          image: scav/colour-service:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080 # I prod bør dette være annen port en hoved-port
            initialDelaySeconds: 20 # Venter før den begynner å sjekke om app'en er klar
            periodSeconds: 1 # Hvor ofte den sjekker
            failureThreshold: 5 # Hvor mange feil som skal til før den konkluderer..
          livenessProbe:
            httpGet:
              path: /health
              port: 8080 # I prod bør dette være annen port en hoved-port
            periodSeconds: 1 # Hvor ofte den sjekker
            failureThreshold: 5 # Hvor mange feil som skal til før den konkluderer..


          env:
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_HEALTH_ENDPOINT
              value: "true"
            - name: REMOTE_SERVICE
              value: "colour-service.default"
            - name: NEW_COLOUR
              value: "success" # Fargene finner dere her: https://beauter.io/docs/colors/
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            limits:
              cpu: "250m"
              memory: "250Mi"
            requests:
              cpu: "200m"
              memory: "100Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: demo-service-green
  labels:
    app: demo-pod-green
spec:
  selector:
    app: demo-pod-green
  ports:
    - port: 7070
      name: http
      targetPort: 8080

