apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-pod
    version: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-pod
      version: default
  template:
    metadata:
      labels:
        app: demo-pod
        version: default
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: demo-pod
        image: scav/colour-service:any
        ports:
        - containerPort: 8080

        env:
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_HEALTH_ENDPOINT
          value: "true"
        - name: REMOTE_SERVICE
          value: "colour-service.default"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          limits:
            cpu: "250m"
            memory: "250Mi"
          requests:
            cpu: "200m"
            memory: "100Mi"
