apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-pod
    version: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-pod
      version: default
  template:
    metadata:
      labels:
        app: demo-pod
        version: default
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: demo-pod
        image: scav/colour-service:latest
        ports:
        - containerPort: 8080

        env:
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_HEALTH_ENDPOINT
          value: "true"
        - name: REMOTE_SERVICE
          value: "colour-service.default"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          limits:
            cpu: "250m"
            memory: "250Mi"
          requests:
            cpu: "200m"
            memory: "100Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: demo-service
  labels:
    app: demo-pod
spec:
  selector:
    app: demo-pod
  ports:
  - port: 7070
    name: http
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lb-service
spec:
  rules:
    - http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: demo-service
                port:
                  number: 7070
