---
apiVersion: v1
kind: Service
metadata:
  name: colour-service
  labels:
    run: colour-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: colour-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: colour-service
spec:
  selector:
    matchLabels:
      run: colour-service
  replicas: 5
  template:
    metadata:
      labels:
        run: colour-service
    spec:
      containers:
        - name: colour-service
          image: scav/colour-service:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8080
          env:
            - name: NEW_COLOUR
              value: "dark"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_HEALTH_ENDPOINT
              value: "true"
            - name: REMOTE_SERVICE
              value: "colour-service.default"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
